services:
  mysql:
    image: mysql:8.0
    container_name: snac-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: snac_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --innodb-buffer-pool-size=1G
      - --max-connections=500
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
