global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'snac-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['{APP_IP}:8080']
        labels:
          application: 'snac-server'
